<a href="https://colab.research.google.com/github/Paris-G/SURI2024/blob/main/Eigen_values_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: eigen values and eigen vectors
#Question): Find the eigen values and eigen vectors of matrix representation

import numpy as np
A = np.array([[2, -1], [1, -1]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:", eigenvectors)


Eigenvalues: [ 1.61803399 -0.61803399]
Eigenvectors: [[0.93417236 0.35682209]
 [0.35682209 0.93417236]]


In [ ]:
# prompt: normalization of a state

import numpy as np

# Define the state vector
state_vector = np.array([1, 1])

# Normalize the state vector
norm = np.linalg.norm(state_vector)
normalized_state_vector = state_vector / np.linalg.norm(state_vector)

# Print the normalized state vector
print("Norm:", norm)
print("Normalized state vector:", normalized_state_vector)


Norm: 1.4142135623730951
Normalized state vector: [0.70710678 0.70710678]


In [ ]:
# prompt: diagonalize a matrix(2,1)

import numpy as np

# Define the matrix
A = np.array([[2, -1], [1, -1]])

# Find the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Create a diagonal matrix from the eigenvalues
D = np.diag(eigenvalues)

# Create a matrix from the eigenvectors
P = eigenvectors

# Compute the inverse of P
P_inv = np.linalg.inv(P)

# Diagonalize the matrix
#A_diagonalized = P @ D @ P_inv

# Print the diagonalized matrix
print("Diagonalized matrix:")
print(A_diagonalized)
print(D)
print(P)


Diagonalized matrix:
[[ 2. -1.]
 [ 1. -1.]]
[[ 1.61803399  0.        ]
 [ 0.         -0.61803399]]
[[0.93417236 0.35682209]
 [0.35682209 0.93417236]]


In [ ]:
# prompt: diagonalize a matrix(2,1)

import numpy as np

# Define the matrix
A = np.array([[2, 4], [3, 5]])

# Find the eigenvalues and eigenvectors of A
eigenvalues, eigenvectors = np.linalg.eig(A)

# Create a diagonal matrix from the eigenvalues
D = np.diag(eigenvalues)

# Create a matrix from the eigenvectors
P = eigenvectors

# Compute the inverse of P
P_inv = np.linalg.inv(P)

# Diagonalize the matrix
A_diagonalized = P @ D @ P_inv

# Print the diagonalized matrix
print("Diagonalized matrix:")
print(A_diagonalized)
print(D)
print(P)


Diagonalized matrix:
[[2. 4.]
 [3. 5.]]
[[-0.27491722  0.        ]
 [ 0.          7.27491722]]
[[-0.86925207 -0.60422718]
 [ 0.49436913 -0.79681209]]
